apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpi_devops
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nodejs_image
        image: kpi_devops
        imagePullPolicy: Never